# Generated by Django 5.2.3 on 2025-06-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dish_list',
        ),
        migrations.AddField(
            model_name='order',
            name='dish',
            field=models.ManyToManyField(to='main.dish'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dish',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
