# Generated by Django 5.2.3 on 2025-06-21 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_basket_dish_remove_order_dish_list_order_dish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
