# Generated by Django 5.2.3 on 2025-06-21 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
