# Generated by Django 5.2.3 on 2025-06-28 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_order_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
